[package]
name = "dbgen"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
serde = { version = "1.0.127", features = ["derive"] }
archlinux-repo-parser = "0.1.6"
libsql = "0.4.0"
url = "2.5.1"
tokio = { version = "1.38.0", features = ["full"] }