[package]
name = "aurparser"
version = "0.1.0"
edition = "2021"

[dependencies]
libsql = "0.4.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"
repoparser = { path = "../repoparser" }
tokio = { version = "1.38.0", features = ["full"] }