name: "Project Test Run"

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Installing Rust
          uses: actions-rust-lang/setup-rust-toolchain@v1
        - name: Download PKG Databases
          run: ./scripts/get_pkgs.sh
        - name: Building with Cargo
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release
        - name: Run DBGen Parse
          run: cargo run --release --bin dbgen
        - name: Run AUR Parser
          run: cargo run --release --bin aurparser
        - uses: actions/upload-artifact@v4
          with:
            name: localdbs
            path: |
              **/local.db
              db/local.db