name: "Project Test Run"

on:
  workflow_dispatch: 
  push:
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Installing Rust
          uses: actions-rust-lang/setup-rust-toolchain@v1
        - name: Download PKG Databases
          run: ./scripts/get_dbs.sh
        - name: Run DBGen Parse
          run: |
                cd packages/dbgen
                cargo build --release
                cargo run --release